In [24]:
class ShoppingCart : 
    def __init__ (self):
        self.items = [] 
        
    def add_items(self , name , quantity) :
        self.items.append((name , quantity)) 
        
        print(f"I added {quantity} {name}s to the shopping cart")
    
    def remove_items (self , name ): 
        for item in self.items: 
            if item[0] == name: 
                self.items.remove(item)
                
        print (f"I removed {name} from the shoppping cart ")
            
    def calculate_sum(self):
        total = sum (item[1] for item in self.items)
        print(f"total sum of items incart is {total}")
        
    def show(self): 
        for item in self.items:
            print (item[0] , item[1])
            
                
        
        

In [25]:
cart1 = ShoppingCart()
cart1

In [26]:
cart1.add_items('banana' , 3)

I added 3 bananas to the shopping cart


In [27]:
cart1.add_items('oranges' , 3)

I added 3 orangess to the shopping cart


In [28]:
cart1.add_items('zeit' , 1)

I added 1 zeits to the shopping cart


In [29]:
cart1.show()

banana 3
oranges 3
zeit 1


In [30]:
cart1.remove_items('oranges')

I removed oranges from the shoppping cart 


In [31]:
cart1.show()

banana 3
zeit 1


In [32]:
cart1.calculate_sum()

total sum of items incart is 4


In [36]:
fibo_list = [0,1]

def fibonacci(num):
    if num < 2:
        print('invalid input')
        
    elif len(fibo_list) == num:
        print('the first', num, 'fibonacci numbers are:', fibo_list)
        print('the' ,num,'th fubonacci number is: ',fibo_list[num-1])
    else:
        fibo_list.append(fibo_list[-1] + fibo_list[-2])
        fibonacci(num)
        
fibonacci(20)


the first 20 fibonacci numbers are: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]
the 20 th fubonacci number is:  4181


In [56]:
# num = list(map(int,input("enter your list").split(",")))
# find = int(input("enter your target"))
# def pairs(num,find):
#     result = []
#     while num:
#         for i in num:
#             s = num.pop
#             i = find - s
#             if i in num:
#                 result.append((i,s))
#         return result        
# pairs(num,find)

In [57]:
import numpy as np

In [ ]:
np.linalg.matrix_rank()
np.linalg.det()
np.linalg.inv()

In [58]:
m = np.array([[1,2,3],[5,4,6],[6,5,8]])

In [59]:
m

array([[1, 2, 3],
       [5, 4, 6],
       [6, 5, 8]])

In [60]:
m.T

array([[1, 5, 6],
       [2, 4, 5],
       [3, 6, 8]])

In [63]:
m.trace()

13

In [64]:
# help(np.trace)

In [65]:
np.linalg.matrix_rank(m)

3

In [66]:
np.linalg.det(m)

-2.9999999999999996

In [69]:
m_i = np.linalg.inv(m)
m_i

array([[-0.66666667,  0.33333333,  0.        ],
       [ 1.33333333,  3.33333333, -3.        ],
       [-0.33333333, -2.33333333,  2.        ]])

In [74]:
m.dot(m_i)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.77156117e-16,  1.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16,  0.00000000e+00,  1.00000000e+00]])

In [87]:
a = np.array([[1,0,0,0,0],[0,0,0,1,0],
             [1,0,3,0,0],[0,0,0,1,0]])
from scipy.sparse import csr_matrix , csc_matrix

In [90]:
# print(a)
s = csr_matrix(a)
print(s)
s.todense()
type(s)

  (0, 0)	1
  (1, 3)	1
  (2, 0)	1
  (2, 2)	3
  (3, 3)	1


scipy.sparse._csr.csr_matrix

In [79]:
import scipy as sp

In [82]:
print(sp.sparse.csc_matrix(a))

  (0, 0)	1
  (2, 0)	1
  (2, 2)	3
  (1, 3)	1
  (3, 3)	1
  (1, 4)	2
  (3, 4)	2


In [94]:
a = np.array([[1,3],[2,3]])
b = np.array([[2,2],[3,3]])
np.tensordot(a,b , axes=0)

array([[[[2, 2],
         [3, 3]],

        [[6, 6],
         [9, 9]]],


       [[[4, 4],
         [6, 6]],

        [[6, 6],
         [9, 9]]]])